name: Test and Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@0.1.1
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  deploy:
    needs: test
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_key: ${{ secrets.GCLOUD_TOKEN }}
      - name: Install Dependencies and Generate Dist
        run: |
          npm i
          npm run prepare
      - name: Set Project and Deploy to App Engine
        run: |
          gcloud config set project active-valve-266110
          gcloud app deploy app.yml
