name: Test and Deploy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@0.1.1
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
